# Generated by Django 3.0.5 on 2025-08-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='public',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=250, unique=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='page',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
